### ISSUE TITLE
Bug / help report

### ISSUE THREAD

**Issue by LeChevalierDOr** [Aeronica/BardMania#12]
**Describe the bug**
The MIDI file didn't work =(

**To Reproduce**
Use a midi file in 1.12.2

**Expected behavior**
I need some help, to help me a midi parameter on my minecraft or solve the bug

**Screenshots**
I don't have a Screenschot

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version : 10

** Attached devices as appropriate. **
 - MIDI Controller ;  I do not know which one to use
 - /

Thanks you in advance

**Comment by Aeronica** [comment]
It appears Liquid Rhythm can import and export MIDI files. It may be able to produce MIDI messages live via it's sequencer. Bard Mania does not have sequencer support.  It only supports Note On/Off messages from non-sequencer devices.

I use a [KeyStation 49](http://m-audio.com/products/view/keystation-49) and [MidiPlus AKM320](http://www.midiplus.com.tw/akm320.htm) keyboard controllers for testing.

Bard Mania is a novelty mod that lets you play musical instruments using human operated interfaces. That is the computer keyboard or and attached MIDI Keyboard.

The built in MIDI file player "/playmidi" command only works in integrated server/LAN mode. It was added simply for demonstration purposes. It does not work in dedicated server.

The reason for no sequencer support is because it is not practical to send long sequences of machine generated MIDI messages over the Internet in real time. The timing is lost, unless the data is buffered timestamped and streamed. It could work to a point, but would there would be a delay. In a multiplayer environment streaming music in this way would negatively impact the game since the stream would be directed to all players near the source. Doing so could cause rubber-banding and desync in general.

Instead I intend to support a server side music library that is replicated to the clients as needed or during periods of low activity. That way I can support musical NPCs, MOBs, jukeboxes, personal background music play lists, etc. That is allow uploading ABC and MML files to build scores for later playback on the clients in a variety of ways. e.g. MOB and/or NPC groups, musical contraptions, etc.

**Comment by Aeronica** [comment]
Some ideas that may help when using a MIDI keyboard with Bard Mania.

By default Bard Mania listens on all channels, but it can be setup to only listen on a single channel. For testing and general use I recommend leaving the default ALL channels setting.

- Close any other programs that use midi devices. Specifically any program where you would select a input device like a MIDI keyboard.

**Comment by LeChevalierDOr** [comment]
Okay and if i use Ableton live or FL STUDIO ? I can ? Play a midi music ?

**Comment by Aeronica** [comment]
Hello @LeChevalierDOr 
It appears you are trying to play the instruments via a software application. Bard Mania does not expose a MIDI Receiver Device Interface to the operating system. It is not possible for Bard Mania to work with other music applications on your PC.

**Comment by Aeronica** [comment]
You can open a new request and suggest a new feature.  If you do please describe how it should work in the context of single and multi-player scenarios.
