### ISSUE TITLE
[Bug] Mod Conflict causing Invisible Instruments.

### ISSUE THREAD

**Issue by Janivire** [Aeronica/BardMania#13]
When Using NoMoreGlowingPots, Instruments will no longer render when in use. Functionality is still there (sound plays, animation moves) only visual problem.

https://pastebin.com/JhWMLSxX

Use an Instrument with This Mod:
https://minecraft.curseforge.com/projects/nomoreglowingpots?gameCategorySlug=mc-mods&projectID=286348

https://i.imgur.com/X0X1ylz.png

 - OS: Win7

Just using a keyboard.

>Current versions of all three mods used
BardMania 0.12.0
Obduscate 0.2.6
GlowingPots 1.0.0

**Comment by Aeronica** [comment]
I see now,  Jabelar's Truly Magical Enchantment Glints is the issue. Jabelar's code replaces the Item rendering code. I'll have to investigate that. I use the item renderer to display my items in a custom render layer.

The fix is pretty simple. I just need to tell Forge to load Bard Mania after "Jabelar's Truly Magical Enchantment Glint". I'll make a release later today.

**Comment by Aeronica** [comment]
2018-10-11 bard-mania_1.12.2-0.14.0-alpha
Fixes
  * [Bug] Mod Conflict causing Invisible Instruments. #13 Fix loads Bard Mania after "Jabelar's Truly Magical Enchantment Glint"
