### ISSUE TITLE
itlt incompatability

### ISSUE THREAD

**Issue by ghost** [Aeronica/BardMania#14]
**Describe the bug**
Bard mania overrides itlt's custom window title.

**To Reproduce**
1. Load the 2 mods "bard-mania" and "itlt" 
2. And then window title is overridden on loading into a world

**Expected behavior**
Bard mania shouldn't interfere with this, a config option to disable the mod's window title feature would solve it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 22

** Attached devices as appropriate. **
 - MIDI Keyboard, MIDI Controller
 - Manufacturer, Model, link to device technical specifications (MIDI support matrix).

**Additional context**

**Comment by Aeronica** [comment]
...BardMania\run\config\bard_mania.cfg

The configuration file already has the option to disable the window title.
        # Player name in window title. Updates on logon and/or changing dimension.
        # Valid values:
        # DISABLED
        # ENABLED
        S:player_name_in_window_title=ENABLED

**Comment by Aeronica** [comment]
Closing as there is a setting to disable the player name in windows title option. For future reference the next time I update or port the mod I will remove the option entirely and not alter the window title. I added the title option originally because OBS Studio had difficulty dealing with two instances of Minecraft running at the same time.
