### ISSUE TITLE
[Feature Request] Determine the length of note according to the time of key pressed

### ISSUE THREAD

**Issue by Snownee** [Aeronica/BardMania#3]
For flute and recorder. I think it will make instruments more realistic.

**Comment by Aeronica** [comment]
Hi,
Bard Mania instruments are based on the Minecraft Noteblock /SoundSystem technology, That is it uses a single ogg file per instrument. No fancy attack, sustain, decay capabilities are available. While it would be more realistic it would not be Minecraft. Not saying I might not attempt to improve it though. I'll keep it in mind.

Thanks for your request.

**Comment by Aeronica** [comment]
I did a bit of research on Starbound instruments, in particular the flute. The technique they use is a 10 second long sound file that slowly fades to nothing. Starbound uses about 7 sound files per instruments, or 7 octaves. That's quite a lot, but does make for nice sounding playback. It's similar to how a sound font stores samples.

So it would be possible for me to do to do something like that in Bard Mania. I have note-off capability built into the MIDI side, but I'd have to see how well that might work for the PC Keyboard mode.

**Comment by Snownee** [comment]
That will be sweet, thanks for your work!

**Comment by Aeronica** [comment]
Update:
Using long samples has a drawback in that they load slower, and having multiple per instrument is less than ideal. Streaming sources are rather limited in number too. Each time you play a note there is a noticeable delay. It is accentuated when using a dedicated server since the network now carries both note-on and note-off traffic., This needs more work. It's rather buggy. Do you know what a cipher is in organ or MIDI terms? It's a note that starts to play, but a note-off command is never received and note continues to play until either the sample ends, or the system is reset.

Initial sustained polyphony notes for MIDI and the PC Keyboard support has been committed to the repository. No button/mouse support for sustained notes in GuiKeyboard yet.

No release at this time.

**Comment by Aeronica** [comment]
2018-08-29 bard-mania_1.12.2-0.8.0-alpha
Initial sustained note support for Flute and Recorder. That is note-on/note-off handling for MIDI and PC Keyboard GUI modes.

Thank you for the feature request @Snownee
